### ISSUE TITLE
Issues with qt 5.15 on linux

### ISSUE THREAD

**Issue by sjh26** [Slicer/SlicerBuildEnvironment#15]
https://discourse.slicer.org/t/error-executing-version-slicer-4-11-0-2020-06-01-linux-amd64-tar-gz-on-ubuntu-16-04/11834/2

https://discourse.slicer.org/t/missing-qt-library-references/11816/2

We may roll back to older images until this is sorted out.  The 4-10 image is the same as the latest before the recent qt changes

@jamesobutler  @jcfr

**Comment by jcfr** [comment]
Look like these modules would need to be improved:
* https://github.com/Slicer/Slicer/blob/master/CMake/SlicerBlockInstallQt.cmake
* https://github.com/Slicer/Slicer/blob/master/CMake/SlicerBlockInstallQtPlugins.cmake

In the mean time, reverting may be a good idea.

**Comment by sjh26** [comment]
Reverted for now: https://github.com/Slicer/DashboardScripts/commit/c6a425944a846d38e57362a5e39f23861dc534cb

**Comment by sjh26** [comment]
- Rolling back to the 5.12.8 image does not work - installed binary is missing libnss3 and libdbus
- slicer-4.10/ 5.11.2 image no longer works due to cmake changes
- The Qt 5.15 version is missing libxkbcommon, and possibly libQt5QmlModels (have not been able to reproduce this)

**Comment by jcfr** [comment]
> Rolling back to the 5.12.8 image does not work - installed binary is missing libnss3 and libdbus

I which environment did you test ? How could I reproduce this issue ?

> image no longer works due to cmake changes

Are we talking about (1) changes in Slicer itself introduced in the past two weeks or (2) the fact we didn't backup the docker image we were recently using

**Comment by sjh26** [comment]
The environment used is this tag: https://hub.docker.com/layers/slicer/buildenv-qt5-centos7/slicer-4.11-2020.05.27/images/sha256-c8e3cde0bd73c1f97a8209b73f91c839ee31b2d0f098598db0e41be73caa7f70?context=explore

I think (2) is the answer, as I seem to have messed up the backup.  The tag referenced above was supposed to the backup, but contains the 5.12.8 environment instead of the 5.11.2 environment.

**Comment by jcfr** [comment]
It turns out I have the docker image locally with Qt 5.11.2, I will push a tag in a few.

**Comment by jcfr** [comment]
Here  is, see [buildenv-qt5-centos7/slicer-4.11-2018.10.17](https://hub.docker.com/layers/slicer/buildenv-qt5-centos7/slicer-4.11-2018.10.17/images/sha256-73551960143845b5f93a4d3f9a7d5fbcacd545a1ef42b6dfbf49746405baa78a?context=repo)

I will now retag `slicer-4.11-2020.05.27`

**Comment by jcfr** [comment]
To summarize, we now have the following tags:
* [buildenv-qt5-centos7/slicer-4.11-2018.10.17](https://hub.docker.com/layers/slicer/buildenv-qt5-centos7/slicer-4.11-2018.10.17/images/sha256-73551960143845b5f93a4d3f9a7d5fbcacd545a1ef42b6dfbf49746405baa78a?context=repo)
* [buildenv-qt5-centos7/slicer-4.12.8-2020.05.27](https://hub.docker.com/layers/slicer/buildenv-qt5-centos7/slicer-4.12.8-2020.05.27/images/sha256-c8e3cde0bd73c1f97a8209b73f91c839ee31b2d0f098598db0e41be73caa7f70?context=repo)

I removed:
* slicer-4.11-2020.05.27

For reference, it turns out that commit https://github.com/Slicer/SlicerBuildEnvironment/commit/133e60c7c8de25c79583e7bef4a440f7d2fd5ae7 with title `Set TAG to slicer-4.11-2020.05.27 ` is in fact associated with Qt 5.12.8

**Comment by sjh26** [comment]
Great, thanks!

**Comment by sjh26** [comment]
I've pulled the buildenv-qt5-centos7/slicer-4.11-2018.10.17 image on metroplex and tried to generate the script from it, but it keeps generating a script that refers to the `latest` tag, instead of `slicer-4.11-2018.10.17`  Can i just manually change that in the script?

**Comment by jcfr** [comment]
:+1: 

To ensure the change are described in the repository and are not overridden by mistake, I suggest to do something  like this:

```bash
ENV_NAME=qt5-centos7
ENV_VERSION=slicer-4.11-2018.10.17

# Download build environment
script=/home/kitware/bin/slicer-buildenv-${ENV_NAME}-${ENV_VERSION}
if [[ ! -f ${script} ]]; then
  docker run --rm slicer/buildenv-${ENV_NAME} > $script
  chmod +x $script
fi

# Update build environment
$script update
# HACK: Workaround limitation of entrypoint.sh (see https://github.com/Slicer/SlicerBuildEnvironment/issues/16)
sed -i /tmp/out -e "s/slicer\/buildenv-${ENV_NAME}:latest/slicer\/buildenv-${ENV_NAME}:${ENV_VERSION}/"

....
```

**Comment by sjh26** [comment]
Don't we need to specify the tag as well in `docker run`?

**Comment by sjh26** [comment]
And am I adding this to the metroplex script or somewhere else?

**Comment by jcfr** [comment]
> Don't we need to specify the tag as well in docker run?

Good catch. I edited the snippet

> And am I adding this to the metroplex script or somewhere else?

Indeed, while drafting the reply ... I forgot to reference  the script to update: https://github.com/Slicer/DashboardScripts/blob/bbda26a7e4c59b37257d722b4dfbad8aa841092f/metroplex.sh#L31-L32

**Comment by jcfr** [comment]
Then, that same snippet would be copied for SlicerSalt here: https://github.com/Slicer/DashboardScripts/blob/bbda26a7e4c59b37257d722b4dfbad8aa841092f/metroplex.sh#L68

Humm ... I am questioning my introduction of `script` variable ... In the past I advocated against it because it prevents easy copy/paste of build command in the terminal.

I will let you decide/simplify as you see fit.

**Comment by sjh26** [comment]
I think its fine here.  The metroplex script is not easily copy-pastable anyway since you have to change directories/set docker args/ etc.  Lots of lines

We technically don't need to copy the snippet for SALT since they will be using the same images for the time being, but we can do it anyway so that it's ready for when they diverge.

**Comment by sjh26** [comment]
https://github.com/Slicer/DashboardScripts/pull/29
