### ISSUE TITLE
Question about packaging extensions

### ISSUE THREAD

**Issue by phcerdan** [Slicer/SlicerBuildEnvironment#7]
So, I have build and packaged Slicer, and now I am building [an extension](https://github.com/Kitware/BoneTextureExtension).

The extension does not provide a `--target package` as the example in the readme.

I guess I can still add it manually as described here: https://www.slicer.org/wiki/Documentation/Nightly/SlicerApplication/ExtensionsManager#How_to_manually_install_an_extension_package.3F
- unpack the packaged slicer (it was packed in tar.gz)
- copy `lib/qt-loadable-modules/*` from the module to the same folder in the unpacked slicer.
- repack with tar  -czf Slicer-XXX-Date.tar.gz SlicerUnpackedFolder`

Is this the recommended way? Thanks!

**Comment by jcfr** [comment]
The instruction in the readme indicates how to build an extension package similar to what would be download from the extensions manager.

In your case, you want to "bundle" the extension in the Slicer package, to do so, you need to build slicer specifying the option `Slicer_EXTENSION_SOURCE_DIRS`.

For example:

```
cmake -DSlicer_EXTENSION_SOURCE_DIRS:STRING=/path/to/ExtensionA;/path/to/ExtensionB /path/to/source/Slicer
```

See https://github.com/Slicer/Slicer/blob/ea79c943d168f637cb3347bda199d47bbb111890/CMakeLists.txt#L1036-L1038

**Comment by phcerdan** [comment]
Awesome, thanks!

**Comment by phcerdan** [comment]
Provided script in #8  to use `Slicer_EXTENSION_SOURCE_DIRS`
